// Exhibition sample catalogue: 30 distinct knobs — 10 per supported shaft, with
// no shape repeated between shafts. Each shaft gets a family whose proportions
// suit how that encoder actually mounts, so the three trays read as three
// different product characters rather than one set printed three times:
//
//   EC11COMPAT    定番グリップ系 — 深い12mmソケットに支えられた、握って回す背高め
//   EC12E24404A8  計測器系       — 目盛り・指針・台座つきの、狙って合わせる系
//   EC12E1240301  低背フラット系 — 軸出代6.2mm/ソケット2.55mm固定に合わせた低く広い形
//
// Baked to STL by `app/bake-samples.ts`.

import {
  DEFAULT_PARAMS,
  SHAFTS,
  clampParams,
  type KnobParams,
  type ShaftType,
} from "./params";

export interface KnobSample {
  /** Ordinal id used for the filename — keeps the set in a stable display order. */
  id: string;
  name: string;
  /** One-line descriptor for the sample card / README. */
  note: string;
  /** Everything except the shaft, which the family supplies. */
  shape: Partial<KnobParams>;
}

/** Display order of the shaft families. */
export const SHAFT_ORDER: ShaftType[] = [
  "EC11COMPAT",
  "EC12E24404A8",
  "EC12E1240301",
];

/** One-line character description of each family, for the index. */
export const FAMILY_NOTE: Record<ShaftType, string> = {
  EC11COMPAT: "定番グリップ系 — 握って回す、背高め・テクスチャ多め",
  EC12E24404A8: "計測器系 — 目盛り・指針・台座、狙って合わせる",
  EC12E1240301: "低背フラット系 — 低く広い、キャップ/ディスク寄り",
};

/**
 * The 30 silhouettes, grouped by shaft. Values are chosen to sit inside every
 * dynamic limit for their own shaft, so `clampParams` never has to rescue them —
 * but it still runs, as it is the single source of truth for validity.
 */
export const SAMPLES: Record<ShaftType, KnobSample[]> = {
  // ── 定番グリップ系 ─────────────────────────────────────────────
  EC11COMPAT: [
    {
      id: "01-straight-flute",
      name: "ストレート縦溝",
      note: "円筒・細かい縦溝30・面取り",
      shape: {
        bodyShape: "round",
        bodyDiameter: 18,
        topDiameter: 18,
        bodyHeight: 18,
        topEdgeStyle: "chamfer",
        topEdgeSize: 1.2,
        topStyle: "flat",
        surfaceTexture: "flutes",
        fluteCount: 30,
        fluteDepth: 0.6,
        indicator: "line",
      },
    },
    {
      id: "02-barrel-scallop",
      name: "樽型スクープ",
      note: "太鼓型・指スクープ6・丸めた肩",
      shape: {
        bodyShape: "round",
        bodyDiameter: 18,
        topDiameter: 18,
        bodyHeight: 18,
        bodyBulge: 4,
        topEdgeStyle: "fillet",
        topEdgeSize: 1.5,
        topStyle: "flat",
        surfaceTexture: "scallops",
        fluteCount: 6,
        fluteDepth: 1.2,
        indicator: "dimple",
      },
    },
    {
      id: "03-hex-bolt",
      name: "六角ボルト",
      note: "六角・角そのまま・平天面",
      shape: {
        bodyShape: "polygon",
        polygonSides: 6,
        cornerRadius: 0,
        bodyDiameter: 22,
        topDiameter: 22,
        bodyHeight: 14,
        topEdgeStyle: "chamfer",
        topEdgeSize: 1.0,
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "line",
      },
    },
    {
      id: "04-dome-diamond",
      name: "ドーム綾目",
      note: "凸ドーム天面・ダイヤ目ローレット",
      shape: {
        bodyShape: "round",
        bodyDiameter: 20,
        topDiameter: 20,
        bodyHeight: 15,
        topEdgeStyle: "none",
        topStyle: "dome",
        topRecessDepth: 4,
        surfaceTexture: "diamond",
        fluteCount: 24,
        knurlAngle: 30,
        indicator: "line",
      },
    },
    {
      id: "05-chickenhead",
      name: "チキンヘッド",
      note: "指針型の嘴・天面指標なし",
      shape: {
        bodyShape: "pointer",
        bodyDiameter: 20,
        topDiameter: 20,
        bodyHeight: 14,
        pointerLength: 10,
        topEdgeStyle: "none",
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "none",
        indicatorAngle: 90,
      },
    },
    {
      id: "06-waist-rings",
      name: "くびれ横溝",
      note: "鼓型のくびれ・横溝8本",
      shape: {
        bodyShape: "round",
        bodyDiameter: 20,
        topDiameter: 20,
        bodyHeight: 20,
        bodyBulge: -3,
        topEdgeStyle: "fillet",
        topEdgeSize: 1.2,
        topStyle: "flat",
        surfaceTexture: "rings",
        fluteCount: 8,
        fluteDepth: 0.5,
        indicator: "line",
      },
    },
    {
      id: "07-taper-helical",
      name: "テーパー斜め目",
      note: "裾広がり・ヘリカル20・すり鉢天面",
      shape: {
        bodyShape: "round",
        bodyDiameter: 26,
        topDiameter: 16,
        bodyHeight: 18,
        topEdgeStyle: "chamfer",
        topEdgeSize: 1.2,
        topStyle: "dish",
        topRecessDepth: 2.6,
        topRimWidth: 1.5,
        surfaceTexture: "helical",
        fluteCount: 20,
        knurlAngle: 25,
        indicator: "line",
      },
    },
    {
      id: "08-lobed-flower",
      name: "花形ロブ",
      note: "波型8山・リセス天面",
      shape: {
        bodyShape: "lobed",
        lobeCount: 8,
        lobeDepth: 1.6,
        bodyDiameter: 24,
        topDiameter: 24,
        bodyHeight: 16,
        topEdgeStyle: "none",
        topStyle: "recess",
        topRecessDepth: 1.8,
        topRimWidth: 2.5,
        surfaceTexture: "none",
        indicator: "dimple",
      },
    },
    {
      id: "09-square-soft",
      name: "角丸スクエア",
      note: "四角・大きめ角丸・リセス天面",
      shape: {
        bodyShape: "polygon",
        polygonSides: 4,
        cornerRadius: 3.5,
        bodyDiameter: 24,
        topDiameter: 24,
        bodyHeight: 16,
        topEdgeStyle: "none",
        topStyle: "recess",
        topRecessDepth: 2.0,
        topRimWidth: 2.0,
        surfaceTexture: "none",
        indicator: "dimple",
      },
    },
    {
      id: "10-tall-rib",
      name: "ノッポ太リブ",
      note: "細身で背高・太い縦リブ16",
      shape: {
        bodyShape: "round",
        bodyDiameter: 16,
        topDiameter: 16,
        bodyHeight: 22,
        topEdgeStyle: "fillet",
        topEdgeSize: 1.2,
        topStyle: "flat",
        surfaceTexture: "flutes",
        fluteCount: 16,
        fluteDepth: 1.0,
        fluteWidthPercent: 110,
        indicator: "line",
      },
    },
  ],

  // ── 計測器系 ───────────────────────────────────────────────────
  EC12E24404A8: [
    {
      id: "01-dial-fullring",
      name: "全周目盛りダイヤル",
      note: "低背円筒・36目盛り・9本ごと長目盛り",
      shape: {
        bodyShape: "round",
        bodyDiameter: 24,
        topDiameter: 24,
        bodyHeight: 13,
        topEdgeStyle: "chamfer",
        topEdgeSize: 1.0,
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "line",
        tickRing: "ticks",
        tickCount: 36,
        tickMajorEvery: 9,
        tickSpan: 360,
      },
    },
    {
      id: "02-arc-dial-flange",
      name: "弧目盛り＋台座",
      note: "270°スケール・フランジ台座φ30",
      shape: {
        bodyShape: "round",
        bodyDiameter: 22,
        topDiameter: 22,
        bodyHeight: 14,
        topEdgeStyle: "chamfer",
        topEdgeSize: 1.0,
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "line",
        tickRing: "ticks",
        tickCount: 11,
        tickMajorEvery: 5,
        tickSpan: 270,
        skirt: "flange",
        skirtDiameter: 30,
        skirtHeight: 3,
      },
    },
    {
      id: "03-pointer-skirt",
      name: "指針＋台座",
      note: "指針型の嘴・フランジ台座φ26",
      shape: {
        bodyShape: "pointer",
        bodyDiameter: 18,
        topDiameter: 18,
        bodyHeight: 12,
        pointerLength: 9,
        topEdgeStyle: "none",
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "none",
        indicatorAngle: 90,
        skirt: "flange",
        skirtDiameter: 26,
        skirtHeight: 2.5,
      },
    },
    {
      id: "04-knurled-collar",
      name: "太ローレットカラー",
      note: "太い縦目16・つまみやすい肩",
      shape: {
        bodyShape: "round",
        bodyDiameter: 20,
        topDiameter: 20,
        bodyHeight: 16,
        topEdgeStyle: "chamfer",
        topEdgeSize: 1.2,
        topStyle: "flat",
        surfaceTexture: "flutes",
        fluteCount: 16,
        fluteDepth: 1.0,
        fluteWidthPercent: 110,
        indicator: "dimple",
      },
    },
    {
      id: "05-deep-cup",
      name: "深リセス・カップ",
      note: "天面を深く3mm掘った器型",
      shape: {
        bodyShape: "round",
        bodyDiameter: 22,
        topDiameter: 22,
        bodyHeight: 18,
        topEdgeStyle: "none",
        topStyle: "recess",
        topRecessDepth: 3.0,
        topRimWidth: 2.0,
        surfaceTexture: "none",
        indicator: "line",
      },
    },
    {
      id: "06-octagon",
      name: "八角",
      note: "八角・小さめ角丸・平天面",
      shape: {
        bodyShape: "polygon",
        polygonSides: 8,
        cornerRadius: 1.0,
        bodyDiameter: 22,
        topDiameter: 22,
        bodyHeight: 14,
        topEdgeStyle: "chamfer",
        topEdgeSize: 1.0,
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "line",
      },
    },
    {
      id: "07-cone-taper",
      name: "円錐テーパー",
      note: "φ26→φ14 の強いテーパー・つるり",
      shape: {
        bodyShape: "round",
        bodyDiameter: 26,
        topDiameter: 14,
        bodyHeight: 16,
        topEdgeStyle: "fillet",
        topEdgeSize: 1.2,
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "line",
      },
    },
    {
      id: "08-triangle",
      name: "角丸三角",
      note: "三角・大きめ角丸・平天面",
      shape: {
        bodyShape: "polygon",
        polygonSides: 3,
        // A 60° corner loses r/sin(30°) = 2r of reach when rounded, so the
        // circumscribed diameter is set well over the others to land at a
        // comparable ~φ22 on the table.
        cornerRadius: 5,
        bodyDiameter: 32,
        topDiameter: 32,
        bodyHeight: 14,
        topEdgeStyle: "chamfer",
        topEdgeSize: 1.0,
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "line",
      },
    },
    {
      id: "09-dome-smooth",
      name: "つるりドーム",
      note: "テクスチャなし・凸ドーム5mm",
      shape: {
        bodyShape: "round",
        bodyDiameter: 20,
        topDiameter: 20,
        bodyHeight: 12,
        topEdgeStyle: "none",
        topStyle: "dome",
        topRecessDepth: 5,
        surfaceTexture: "none",
        indicator: "dimple",
      },
    },
    {
      id: "10-mushroom",
      name: "キノコ型",
      note: "φ16→φ24 の逆テーパー・大きな丸肩",
      shape: {
        bodyShape: "round",
        bodyDiameter: 16,
        topDiameter: 24,
        bodyHeight: 14,
        topEdgeStyle: "fillet",
        topEdgeSize: 2.0,
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "line",
      },
    },
  ],

  // ── 低背フラット系 ─────────────────────────────────────────────
  // Socket depth is pinned at 2.55mm by the shaft's fixedHoleDepth, and the
  // shaft only stands 6.2mm proud — so this family stays low and wide, where a
  // tall knob would be top-heavy on the mount.
  EC12E1240301: [
    {
      id: "01-flat-disc",
      name: "薄型ディスク",
      note: "φ26×H9 の素の円盤・面取り",
      shape: {
        bodyShape: "round",
        bodyDiameter: 26,
        topDiameter: 26,
        bodyHeight: 9,
        topEdgeStyle: "chamfer",
        topEdgeSize: 1.0,
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "line",
      },
    },
    {
      id: "02-coin-edge",
      name: "コインエッジ",
      note: "横溝6本の積層風・丸めた肩",
      shape: {
        bodyShape: "round",
        bodyDiameter: 24,
        topDiameter: 24,
        bodyHeight: 10,
        topEdgeStyle: "fillet",
        topEdgeSize: 1.0,
        topStyle: "flat",
        surfaceTexture: "rings",
        fluteCount: 6,
        fluteDepth: 0.5,
        indicator: "line",
      },
    },
    {
      id: "03-wide-dish",
      name: "皿型ワイド",
      note: "φ28・すり鉢天面3mm・指を置ける",
      shape: {
        bodyShape: "round",
        bodyDiameter: 28,
        topDiameter: 28,
        bodyHeight: 10,
        topEdgeStyle: "chamfer",
        topEdgeSize: 1.2,
        topStyle: "dish",
        topRecessDepth: 3.0,
        topRimWidth: 2.0,
        surfaceTexture: "none",
        indicator: "dimple",
      },
    },
    {
      id: "04-hex-low",
      name: "低背六角",
      note: "六角・角そのまま・H9",
      shape: {
        bodyShape: "polygon",
        polygonSides: 6,
        cornerRadius: 0,
        bodyDiameter: 22,
        topDiameter: 22,
        bodyHeight: 9,
        topEdgeStyle: "chamfer",
        topEdgeSize: 0.8,
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "line",
      },
    },
    {
      id: "05-puck-flute",
      name: "縦溝パック",
      note: "細かい縦溝36の低背パック",
      shape: {
        bodyShape: "round",
        bodyDiameter: 22,
        topDiameter: 22,
        bodyHeight: 12,
        topEdgeStyle: "chamfer",
        topEdgeSize: 1.0,
        topStyle: "flat",
        surfaceTexture: "flutes",
        fluteCount: 36,
        fluteDepth: 0.6,
        indicator: "line",
      },
    },
    {
      id: "06-lobed-low",
      name: "低背ロブ",
      note: "波型6山・浅いリセス天面",
      shape: {
        bodyShape: "lobed",
        lobeCount: 6,
        lobeDepth: 1.8,
        bodyDiameter: 26,
        topDiameter: 26,
        bodyHeight: 10,
        topEdgeStyle: "none",
        topStyle: "recess",
        topRecessDepth: 1.6,
        topRimWidth: 2.5,
        surfaceTexture: "none",
        indicator: "dimple",
      },
    },
    {
      id: "07-dome-cap",
      name: "ドームキャップ",
      note: "丸屋根5mm・ボタンのような佇まい",
      shape: {
        bodyShape: "round",
        bodyDiameter: 22,
        topDiameter: 22,
        bodyHeight: 10,
        topEdgeStyle: "none",
        topStyle: "dome",
        topRecessDepth: 5,
        surfaceTexture: "none",
        indicator: "dimple",
      },
    },
    {
      id: "08-square-low",
      name: "低背スクエア",
      note: "四角・角丸4mm・H9",
      shape: {
        bodyShape: "polygon",
        polygonSides: 4,
        cornerRadius: 4,
        bodyDiameter: 22,
        topDiameter: 22,
        bodyHeight: 9,
        topEdgeStyle: "chamfer",
        topEdgeSize: 0.8,
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "line",
        indicatorReach: 6.5,
      },
    },
    {
      id: "09-pointer-low",
      name: "低背指針",
      note: "薄い指針型・嘴8mm",
      shape: {
        bodyShape: "pointer",
        bodyDiameter: 20,
        topDiameter: 20,
        bodyHeight: 8,
        pointerLength: 8,
        topEdgeStyle: "none",
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "none",
        indicatorAngle: 90,
      },
    },
    {
      id: "10-tick-disc",
      name: "目盛りディスク",
      note: "φ28×H8・全周24目盛り",
      shape: {
        bodyShape: "round",
        bodyDiameter: 28,
        topDiameter: 28,
        bodyHeight: 8,
        topEdgeStyle: "chamfer",
        topEdgeSize: 0.8,
        topStyle: "flat",
        surfaceTexture: "none",
        indicator: "dimple",
        tickRing: "ticks",
        tickCount: 24,
        tickMajorEvery: 6,
        tickSpan: 360,
      },
    },
  ],
};

/**
 * Complete, validated params for one sample on its shaft. The socket depth comes
 * from the shaft's own recommendation (the hollow low-profile shaft pins it via
 * `fixedHoleDepth`, which `clampParams` applies).
 */
export function sampleParams(sample: KnobSample, shaft: ShaftType): KnobParams {
  const spec = SHAFTS[shaft];
  return clampParams({
    ...DEFAULT_PARAMS,
    ...sample.shape,
    shaft,
    shaftHoleDepth: spec.recommendedHoleDepth ?? DEFAULT_PARAMS.shaftHoleDepth,
  });
}
